### ISSUE TITLE
How to load roms from local directory hosted on the webrcade server

### ISSUE THREAD

**Issue by rocheston** [webrcade/webrcade#34]
I have hosted webrcade on my local server at home. I want to point to a directory on the host machine to the roms location. (Instead of using Dropbox folder). How to achieve this? Adding one rom at a time is pain. I want to simply point to local directory and webrcade should process the metadata and add all the roms to json. 

My roms collection is located on the same machine as the webrcade web server Linux.

**Comment by raz0red** [comment]
Yeah, this is absolutely something that should be supported. Thanks for submitting!

**Comment by geezer500** [comment]
+1 for this... I've tried the docker image...  you could just map your roms folder directly into the container.
So it would be a matter of allowing webrcade to load roms from a local (internal to the container) folder.
You can hardcode it as the container would allow you to map to that path.

**Comment by raz0red** [comment]
Relative path support is something I will be working on soon. At that point, this should be very straight-forward.

**Comment by KingIzzymon** [comment]
@rocheston & @geezer500

# Installation

Install via docker cli:

```sh
docker run -rm \
  --name=webrcade \
  -p 80:80 \
  -v /path/to/content:/var/www/html/content \
  --restart unless-stopped \
  webrcade/webrcade:latest
```

or deploy with docker-compose:

```yaml
version: "3"
services:
  webrcade:
    image: webrcade/webrcade:latest
    container_name: webrcade
    volumes:
      - /path/to/content:/var/www/html/content # Docker for Windows use "/c/path/to/content"
    ports:
      - 80:80
    restart: unless-stopped
```

## Setup

The `/path/to/content` location will be accessible to the webRcade server so it can host your games and feeds locally.

Its recommended to have your ROMs in their own system folder structure:

### Example Structure
    - nes/Super Mario Bros. (U).nes (or .zip)
    - gba/Sonic Advance (U).gba (or .zip)
    - myfeed.json

When setting up games/feeds with the editor, use the following example URLs:

### Example URLs (no http://*** needed)
    - /content/nes/Sonic Advance (U).nes
    - /content/gba/Sonic Advance (U).gba
    - /content/myfeed.json
